# permissions for end users to view mycustomkinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycustomkind-viewer-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - mycustomkinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - mycustomkinds/status
  verbs:
  - get
